RayTracingRentalsMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RayTracingRentalsMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RayTracingRentalsMVC/Controllers/RentalOrderController.cs
using RayTracingRental.Data;
using RayTracingRentals.Models.RentalOrders;
using RayTracingRentals.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RayTracingRentalsMVC.Controllers
{
    public class RentalOrderController : Controller
    {
        // GET: RentalOrder
        public ActionResult Index()
        {
            var rentalOrder = CreateRentalOrderService();
            var order = rentalOrder.GetRentalOrders();
            return View(order);
        }

        public ActionResult Create()
        {
            List<RentalStore> stores = (new RentalStoreService()).GetRentalStoreList().ToList();
            ViewBag.RentalStoreId = stores.Select(o => new SelectListItem
            {
                Value = o.RentalStoreId.ToString(),
                Text = o.StoreName,
            });
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RentalOrderCreate order)
        {
            if (!ModelState.IsValid) return View(order);

            var service = CreateRentalOrderService();

            if (service.CreateRentalOrder(order))
            {
                TempData["SaveResult"] = "The order has been created.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "The order could not be created");
            return View(order);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateRentalOrderService();
            var model = svc.GetRentalOrderById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateRentalOrderService().GetRentalOrderById(id);

            List<RentalStore> stores = (new RentalStoreService()).GetRentalStoreList().ToList();
            ViewBag.RentalStoreId = stores.Select(o => new SelectListItem()
            {
                Value = o.RentalStoreId.ToString(),
                Text = o.StoreName,
                Selected = service.RentalStoreId == o.RentalStoreId
            });

            return View(new RentalOrderEdit
            {
                RentalStoreId = service.RentalStoreId,
                RentalOrderId = service.RentalOrderId,
                Name = service.Name,
               Clerk = service.Clerk,
               Returned = service.Returned
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, RentalOrderEdit edit)
        {
            if (!ModelState.IsValid) return View(edit);

            if (edit.RentalOrderId != id)
            {
                ModelState.AddModelError("", "Id does not match.");
                return View(edit);
            }

            var service = CreateRentalOrderService();

            if (service.UpdateRentalOrder(edit))
            {
                TempData["SaveResult"] = "The rental order has been updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "The rental order could not be updated.");
            return View(edit);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateRentalOrderService();
            var model = svc.GetRentalOrderById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteById(int id)
        {
            var service = CreateRentalOrderService();
            service.DeleteRentalOrder(id);
            
            TempData["SaveResult"] = "The rental order was deleted.";
            return RedirectToAction("Index");
        }

        private RentalOrderService CreateRentalOrderService()
        {
            var rentalService = new RentalOrderService();
            return rentalService;
        }
    }
}

RayTracingRentalsMVC/Controllers/RentalStoreController.cs
using RayTracingRentals.Data;
using RayTracingRentals.Models.TheRentalStore;
using RayTracingRentals.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RayTracingRentalsMVC.Controllers
{
    public class RentalStoreController : Controller
    {
        // GET: RentalStore
        public ActionResult Index()
        {
            var rentalOrder = CreateRentalStoreService();
            var order = rentalOrder.GetRentalStores();
            return View(order);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RentalStoreCreate store)
        {
            if (!ModelState.IsValid) return View(store);

            var service = CreateRentalStoreService();

            if (service.CreateRentalStore(store))
            {
                TempData["SaveResult"] = "The store has been created.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "The store could not be created");
            return View(store);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateRentalStoreService();
            var model = svc.GetRentalStoreById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateRentalStoreService();
            var detail = service.GetRentalStoreById(id);
            var model =
                new RentalStoreEdit
                {
                    RentalStoreId = detail.RentalStoreId,
                    StoreName = detail.StoreName,
                    Location = detail.Location,
                    PhoneNumber = detail.PhoneNumber,
                    Website = detail.Website
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, RentalStoreEdit edit)
        {
            if (!ModelState.IsValid) return View(edit);

            if (edit.RentalStoreId != id)
            {
                ModelState.AddModelError("", "Id does not match.");
                return View(edit);
            }

            var service = CreateRentalStoreService();

            if (service.UpdateRentalStore(edit))
            {
                TempData["SaveResult"] = "The rental store has been updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "The rental store could not be updated.");
            return View(edit);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateRentalStoreService();
            var model = svc.GetRentalStoreById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteById(int id)
        {
            var service = CreateRentalStoreService();
            service.DeleteRentalStore(id);

            TempData["SaveResult"] = "The rental store was deleted.";
            return RedirectToAction("Index");
        }


        private RentalStoreService CreateRentalStoreService()
        {
            var rentalService = new RentalStoreService();
            return rentalService;
        }
    }
}

RayTracingRentalsMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>About Ray-Tracing Rentals</h2>
<h3>A game rental management system!</h3>

<p>Use this application to keep track of products, customers, orders, and stores. You can also edit, update, and delete these as well! </p>

RayTracingRentalsMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>Contact Us</h2>
<h3>We are available at:</h3>

<address>
    Mars Rover<br />
    Red Rock, Mars <br />
    <abbr title="Phone">P:</abbr>
    123.456.MARS
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Ray@TracingSupport.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Ray@TracingMarket.comm</a>
</address>

RayTracingRentalsMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Welcome to Ray-Tracing Rentals!</h1>
    <p class="lead">Ray-Tracing Rentals is a up and coming game rental service! FIrst, register a account, then to create, view, update, or delete a rental store please click the Rental Store button below or the Store button on the navigation bar.</p>
    @if (User.Identity.IsAuthenticated)
    {
        <input type="button" class="btn btn-primary btn-lg" value="Rental Store" onclick="location.href='@Url.Action("Index", "RentalStore")'" />
    }
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Rental Order</h2>
        <p>
            This is where you can create, view, update, or delete a rental order. Each rental order will need a rental store before creating.
        </p>
        @if (User.Identity.IsAuthenticated)
        {
            <input type="button" class="btn btn-default" value="Rental Order" onclick="location.href='@Url.Action("Index", "RentalOrder")'" />
        }

    </div>
    <div class="col-md-4">
        <h2>Product</h2>
        <p>This is where you can create, view, update, and delete a product, each product will need a rental order before creating.</p>
        @if (User.Identity.IsAuthenticated)
        {
            <input type="button" class="btn btn-default" value="Product" onclick="location.href='@Url.Action("Index", "Product")'" />
        }
    </div>
    <div class="col-md-4">
        <h2>Customer</h2>
        <p>This is where a customer can be created, viewed, updated, and deleted. You will also need to create a rental order before creating a customer.</p>
        @if (User.Identity.IsAuthenticated)
        {
            <input type="button" class="btn btn-default" value="Customer" onclick="location.href='@Url.Action("Index", "Customer")'" />
        }
    </div>
</div>